// FIFA World Cup 2026 Schedule & Settings Data

window.TEAM_FLAGS = {
  "Mexico": "mx",
  "South Africa": "za",
  "South Korea": "kr",
  "Czechia": "cz",
  "Canada": "ca",
  "Bosnia and Herzegovina": "ba",
  "Qatar": "qa",
  "Switzerland": "ch",
  "Brazil": "br",
  "Morocco": "ma",
  "Haiti": "ht",
  "Scotland": "gb-sct",
  "United States": "us",
  "Paraguay": "py",
  "Australia": "au",
  "Turkey": "tr",
  "Germany": "de",
  "Curaçao": "cw",
  "Netherlands": "nl",
  "Japan": "jp",
  "Ivory Coast": "ci",
  "Ecuador": "ec",
  "Sweden": "se",
  "Tunisia": "tn",
  "Spain": "es",
  "Cape Verde": "cv",
  "Belgium": "be",
  "Egypt": "eg",
  "Saudi Arabia": "sa",
  "Uruguay": "uy",
  "Iran": "ir",
  "New Zealand": "nz",
  "France": "fr",
  "Senegal": "sn",
  "Iraq": "iq",
  "Norway": "no",
  "Argentina": "ar",
  "Algeria": "dz",
  "Austria": "at",
  "Jordan": "jo",
  "Portugal": "pt",
  "DR Congo": "cd",
  "England": "gb-eng",
  "Croatia": "hr",
  "Ghana": "gh",
  "Panama": "pa",
  "Uzbekistan": "uz",
  "Colombia": "co"
};

window.WORLD_CUP_DATA = {
  "tournament": "FIFA World Cup 2026",
  "teams_count": 48,
  "total_matches": 104,
  "group_stage": [
    { "group": "Group A", "date": "12/6", "time": "02:00", "team1": "Mexico", "team2": "South Africa" },
    { "group": "Group A", "date": "12/6", "time": "09:00", "team1": "South Korea", "team2": "Czechia" },
    { "group": "Group B", "date": "13/6", "time": "02:00", "team1": "Canada", "team2": "Bosnia and Herzegovina" },
    { "group": "Group D", "date": "13/6", "time": "08:00", "team1": "United States", "team2": "Paraguay" },
    { "group": "Group B", "date": "14/6", "time": "02:00", "team1": "Qatar", "team2": "Switzerland" },
    { "group": "Group C", "date": "14/6", "time": "05:00", "team1": "Brazil", "team2": "Morocco" },
    { "group": "Group C", "date": "14/6", "time": "08:00", "team1": "Haiti", "team2": "Scotland" },
    { "group": "Group D", "date": "14/6", "time": "11:00", "team1": "Australia", "team2": "Turkey" },
    { "group": "Group E", "date": "15/6", "time": "00:00", "team1": "Germany", "team2": "Curaçao" },
    { "group": "Group F", "date": "15/6", "time": "03:00", "team1": "Netherlands", "team2": "Japan" },
    { "group": "Group E", "date": "15/6", "time": "06:00", "team1": "Ivory Coast", "team2": "Ecuador" },
    { "group": "Group F", "date": "15/6", "time": "09:00", "team1": "Sweden", "team2": "Tunisia" },
    { "group": "Group H", "date": "15/6", "time": "23:00", "team1": "Spain", "team2": "Cape Verde" },
    { "group": "Group G", "date": "16/6", "time": "02:00", "team1": "Belgium", "team2": "Egypt" },
    { "group": "Group H", "date": "16/6", "time": "05:00", "team1": "Saudi Arabia", "team2": "Uruguay" },
    { "group": "Group G", "date": "16/6", "time": "08:00", "team1": "Iran", "team2": "New Zealand" },
    { "group": "Group I", "date": "17/6", "time": "02:00", "team1": "France", "team2": "Senegal" },
    { "group": "Group I", "date": "17/6", "time": "05:00", "team1": "Iraq", "team2": "Norway" },
    { "group": "Group J", "date": "17/6", "time": "08:00", "team1": "Argentina", "team2": "Algeria" },
    { "group": "Group J", "date": "17/6", "time": "11:00", "team1": "Austria", "team2": "Jordan" },
    { "group": "Group K", "date": "18/6", "time": "00:00", "team1": "Portugal", "team2": "DR Congo" },
    { "group": "Group L", "date": "18/6", "time": "03:00", "team1": "England", "team2": "Croatia" },
    { "group": "Group L", "date": "18/6", "time": "06:00", "team1": "Ghana", "team2": "Panama" },
    { "group": "Group K", "date": "18/6", "time": "09:00", "team1": "Uzbekistan", "team2": "Colombia" },
    { "group": "Group A", "date": "18/6", "time": "23:00", "team1": "Czechia", "team2": "South Africa" },
    { "group": "Group B", "date": "19/6", "time": "02:00", "team1": "Switzerland", "team2": "Bosnia and Herzegovina" },
    { "group": "Group B", "date": "19/6", "time": "05:00", "team1": "Canada", "team2": "Qatar" },
    { "group": "Group A", "date": "19/6", "time": "08:00", "team1": "Mexico", "team2": "South Korea" },
    { "group": "Group D", "date": "20/6", "time": "02:00", "team1": "United States", "team2": "Australia" },
    { "group": "Group C", "date": "20/6", "time": "05:00", "team1": "Scotland", "team2": "Morocco" },
    { "group": "Group C", "date": "20/6", "time": "07:30", "team1": "Brazil", "team2": "Haiti" },
    { "group": "Group D", "date": "20/6", "time": "10:00", "team1": "Turkey", "team2": "Paraguay" },
    { "group": "Group F", "date": "21/6", "time": "00:00", "team1": "Netherlands", "team2": "Sweden" },
    { "group": "Group E", "date": "21/6", "time": "03:00", "team1": "Germany", "team2": "Ivory Coast" },
    { "group": "Group E", "date": "21/6", "time": "07:00", "team1": "Ecuador", "team2": "Curaçao" },
    { "group": "Group F", "date": "21/6", "time": "11:00", "team1": "Tunisia", "team2": "Japan" },
    { "group": "Group H", "date": "21/6", "time": "23:00", "team1": "Spain", "team2": "Saudi Arabia" },
    { "group": "Group G", "date": "22/6", "time": "02:00", "team1": "Belgium", "team2": "Iran" },
    { "group": "Group H", "date": "22/6", "time": "05:00", "team1": "Uruguay", "team2": "Cape Verde" },
    { "group": "Group G", "date": "22/6", "time": "08:00", "team1": "New Zealand", "team2": "Egypt" },
    { "group": "Group J", "date": "23/6", "time": "00:00", "team1": "Argentina", "team2": "Austria" },
    { "group": "Group I", "date": "23/6", "time": "04:00", "team1": "France", "team2": "Iraq" },
    { "group": "Group I", "date": "23/6", "time": "07:00", "team1": "Norway", "team2": "Senegal" },
    { "group": "Group J", "date": "23/6", "time": "10:00", "team1": "Jordan", "team2": "Algeria" },
    { "group": "Group K", "date": "24/6", "time": "00:00", "team1": "Portugal", "team2": "Uzbekistan" },
    { "group": "Group L", "date": "24/6", "time": "03:00", "team1": "England", "team2": "Ghana" },
    { "group": "Group L", "date": "24/6", "time": "06:00", "team1": "Panama", "team2": "Croatia" },
    { "group": "Group K", "date": "24/6", "time": "09:00", "team1": "Colombia", "team2": "DR Congo" },
    { "group": "Group B", "date": "25/6", "time": "02:00", "team1": "Switzerland", "team2": "Canada" },
    { "group": "Group B", "date": "25/6", "time": "02:00", "team1": "Bosnia and Herzegovina", "team2": "Qatar" },
    { "group": "Group C", "date": "25/6", "time": "05:00", "team1": "Morocco", "team2": "Haiti" },
    { "group": "Group C", "date": "25/6", "time": "05:00", "team1": "Scotland", "team2": "Brazil" },
    { "group": "Group A", "date": "25/6", "time": "08:00", "team1": "South Africa", "team2": "South Korea" },
    { "group": "Group A", "date": "25/6", "time": "08:00", "team1": "Czechia", "team2": "Mexico" },
    { "group": "Group E", "date": "26/6", "time": "03:00", "team1": "Curaçao", "team2": "Ivory Coast" },
    { "group": "Group E", "date": "26/6", "time": "03:00", "team1": "Ecuador", "team2": "Germany" },
    { "group": "Group F", "date": "26/6", "time": "06:00", "team1": "Tunisia", "team2": "Netherlands" },
    { "group": "Group F", "date": "26/6", "time": "06:00", "team1": "Japan", "team2": "Sweden" },
    { "group": "Group D", "date": "26/6", "time": "09:00", "team1": "Turkey", "team2": "United States" },
    { "group": "Group D", "date": "26/6", "time": "09:00", "team1": "Paraguay", "team2": "Australia" },
    { "group": "Group I", "date": "27/6", "time": "02:00", "team1": "Norway", "team2": "France" },
    { "group": "Group I", "date": "27/6", "time": "02:00", "team1": "Senegal", "team2": "Iraq" },
    { "group": "Group H", "date": "27/6", "time": "07:00", "team1": "Cape Verde", "team2": "Saudi Arabia" },
    { "group": "Group H", "date": "27/6", "time": "07:00", "team1": "Uruguay", "team2": "Spain" },
    { "group": "Group G", "date": "27/6", "time": "10:00", "team1": "New Zealand", "team2": "Belgium" },
    { "group": "Group G", "date": "27/6", "time": "10:00", "team1": "Egypt", "team2": "Iran" },
    { "group": "Group L", "date": "28/6", "time": "04:00", "team1": "Panama", "team2": "England" },
    { "group": "Group L", "date": "28/6", "time": "04:00", "team1": "Croatia", "team2": "Ghana" },
    { "group": "Group K", "date": "28/6", "time": "06:30", "team1": "Colombia", "team2": "Portugal" },
    { "group": "Group K", "date": "28/6", "time": "06:30", "team1": "DR Congo", "team2": "Uzbekistan" },
    { "group": "Group J", "date": "28/6", "time": "09:00", "team1": "Algeria", "team2": "Austria" },
    { "group": "Group J", "date": "28/6", "time": "09:00", "team1": "Jordan", "team2": "Argentina" }
  ],
  "knockout_stage": [
    { "match_id": 73, "group": "Round of 32", "date": "29/6", "time": "02:00", "team1": "Runner-up Group A", "team2": "Runner-up Group B", "team1_seed": "2A", "team2_seed": "2B", "venue": "SoFi Stadium, Inglewood", "top10": false, "top20": true },
    { "match_id": 74, "group": "Round of 32", "date": "30/6", "time": "03:30", "team1": "Winner Group E", "team2": "3rd Group A/B/C/D/F", "team1_seed": "1E", "team2_seed": "3rd", "venue": "Gillette Stadium, Foxborough", "top10": false, "top20": true },
    { "match_id": 75, "group": "Round of 32", "date": "30/6", "time": "08:00", "team1": "Winner Group F", "team2": "Runner-up Group C", "team1_seed": "1F", "team2_seed": "2C", "venue": "Estadio BBVA, Guadalupe", "top10": false, "top20": true },
    { "match_id": 76, "group": "Round of 32", "date": "29/6", "time": "09:00", "team1": "Winner Group C", "team2": "Runner-up Group F", "team1_seed": "1C", "team2_seed": "2F", "venue": "NRG Stadium, Houston", "top10": false, "top20": true },
    { "match_id": 77, "group": "Round of 32", "date": "1/7", "time": "04:00", "team1": "Winner Group I", "team2": "3rd Group C/D/F/G/H", "team1_seed": "1I", "team2_seed": "3rd", "venue": "MetLife Stadium, East Rutherford", "top10": false, "top20": true },
    { "match_id": 78, "group": "Round of 32", "date": "1/7", "time": "09:00", "team1": "Runner-up Group E", "team2": "Runner-up Group I", "team1_seed": "2E", "team2_seed": "2I", "venue": "AT&T Stadium, Arlington", "top10": false, "top20": true },
    { "match_id": 79, "group": "Round of 32", "date": "1/7", "time": "00:00", "team1": "Winner Group A", "team2": "3rd Group C/E/F/H/I", "team1_seed": "1A", "team2_seed": "3rd", "venue": "Estadio Azteca, Mexico City", "top10": false, "top20": true },
    { "match_id": 80, "group": "Round of 32", "date": "1/7", "time": "07:30", "team1": "Winner Group L", "team2": "3rd Group E/H/I/J/K", "team1_seed": "1L", "team2_seed": "3rd", "venue": "Mercedes-Benz Stadium, Atlanta", "top10": false, "top20": true },
    { "match_id": 81, "group": "Round of 32", "date": "2/7", "time": "09:30", "team1": "Winner Group D", "team2": "3rd Group B/E/F/I/J", "team1_seed": "1D", "team2_seed": "3rd", "venue": "Levi's Stadium, Santa Clara", "top10": false, "top20": true },
    { "match_id": 82, "group": "Round of 32", "date": "3/7", "time": "03:30", "team1": "Winner Group G", "team2": "3rd Group A/E/H/I/J", "team1_seed": "1G", "team2_seed": "3rd", "venue": "Lumen Field, Seattle", "top10": false, "top20": true },
    { "match_id": 83, "group": "Round of 32", "date": "2/7", "time": "04:30", "team1": "Runner-up Group K", "team2": "Runner-up Group L", "team1_seed": "2K", "team2_seed": "2L", "venue": "BMO Field, Toronto", "top10": false, "top20": true },
    { "match_id": 84, "group": "Round of 32", "date": "3/7", "time": "08:00", "team1": "Winner Group H", "team2": "Runner-up Group J", "team1_seed": "1H", "team2_seed": "2J", "venue": "SoFi Stadium, Inglewood", "top10": false, "top20": true },
    { "match_id": 85, "group": "Round of 32", "date": "4/7", "time": "02:00", "team1": "Winner Group B", "team2": "3rd Group E/F/G/I/J", "team1_seed": "1B", "team2_seed": "3rd", "venue": "Lincoln Financial Field, Philadelphia", "top10": false, "top20": true },
    { "match_id": 86, "group": "Round of 32", "date": "5/7", "time": "09:30", "team1": "Winner Group J", "team2": "Runner-up Group H", "team1_seed": "1J", "team2_seed": "2H", "venue": "MetLife Stadium, East Rutherford", "top10": false, "top20": true },
    { "match_id": 87, "group": "Round of 32", "date": "4/7", "time": "02:30", "team1": "Winner Group K", "team2": "3rd Group D/E/I/J/L", "team1_seed": "1K", "team2_seed": "3rd", "venue": "NRG Stadium, Houston", "top10": false, "top20": true },
    { "match_id": 88, "group": "Round of 32", "date": "5/7", "time": "08:30", "team1": "Runner-up Group D", "team2": "Runner-up Group G", "team1_seed": "2D", "team2_seed": "2G", "venue": "AT&T Stadium, Arlington", "top10": false, "top20": true },
    { "match_id": 89, "group": "Round of 16", "date": "4/7", "time": "03:00", "team1": "Winner Match 74", "team2": "Winner Match 77", "team1_seed": "W74", "team2_seed": "W77", "venue": "Lincoln Financial Field, Philadelphia", "top10": false, "top20": true },
    { "match_id": 90, "group": "Round of 16", "date": "5/7", "time": "08:00", "team1": "Winner Match 73", "team2": "Winner Match 75", "team1_seed": "W73", "team2_seed": "W75", "venue": "MetLife Stadium, East Rutherford", "top10": false, "top20": true },
    { "match_id": 91, "group": "Round of 16", "date": "5/7", "time": "03:30", "team1": "Winner Match 76", "team2": "Winner Match 78", "team1_seed": "W76", "team2_seed": "W78", "venue": "BC Place, Vancouver", "top10": false, "top20": true },
    { "match_id": 92, "group": "Round of 16", "date": "4/7", "time": "08:00", "team1": "Winner Match 79", "team2": "Winner Match 80", "team1_seed": "W79", "team2_seed": "W80", "venue": "NRG Stadium, Houston", "top10": false, "top20": true },
    { "match_id": 93, "group": "Round of 16", "date": "6/7", "time": "04:00", "team1": "Winner Match 83", "team2": "Winner Match 84", "team1_seed": "W83", "team2_seed": "W84", "venue": "AT&T Stadium, Arlington", "top10": false, "top20": true },
    { "match_id": 94, "group": "Round of 16", "date": "6/7", "time": "08:00", "team1": "Winner Match 81", "team2": "Winner Match 82", "team1_seed": "W81", "team2_seed": "W82", "venue": "Lumen Field, Seattle", "top10": false, "top20": true },
    { "match_id": 95, "group": "Round of 16", "date": "7/7", "time": "04:00", "team1": "Winner Match 85", "team2": "Winner Match 86", "team1_seed": "W85", "team2_seed": "W86", "venue": "Mercedes-Benz Stadium, Atlanta", "top10": false, "top20": true },
    { "match_id": 96, "group": "Round of 16", "date": "7/7", "time": "08:00", "team1": "Winner Match 87", "team2": "Winner Match 88", "team1_seed": "W87", "team2_seed": "W88", "venue": "BC Place, Vancouver", "top10": false, "top20": true },
    { "match_id": 97, "group": "Quarter-final", "date": "9/7", "time": "07:30", "team1": "Winner Match 89", "team2": "Winner Match 90", "team1_seed": "W89", "team2_seed": "W90", "venue": "Gillette Stadium, Foxborough", "top10": true, "top20": true },
    { "match_id": 98, "group": "Quarter-final", "date": "10/7", "time": "07:30", "team1": "Winner Match 93", "team2": "Winner Match 94", "team1_seed": "W93", "team2_seed": "W94", "venue": "SoFi Stadium, Inglewood", "top10": true, "top20": true },
    { "match_id": 99, "group": "Quarter-final", "date": "11/7", "time": "07:30", "team1": "Winner Match 91", "team2": "Winner Match 92", "team1_seed": "W91", "team2_seed": "W92", "venue": "Hard Rock Stadium, Miami Gardens", "top10": true, "top20": true },
    { "match_id": 100, "group": "Quarter-final", "date": "12/7", "time": "07:30", "team1": "Winner Match 95", "team2": "Winner Match 96", "team1_seed": "W95", "team2_seed": "W96", "venue": "Arrowhead Stadium, Kansas City", "top10": true, "top20": true },
    { "match_id": 101, "group": "Semi-final", "date": "14/7", "time": "07:30", "team1": "Winner Match 97", "team2": "Winner Match 98", "team1_seed": "W97", "team2_seed": "W98", "venue": "AT&T Stadium, Arlington", "top10": true, "top20": true },
    { "match_id": 102, "group": "Semi-final", "date": "15/7", "time": "07:30", "team1": "Winner Match 99", "team2": "Winner Match 100", "team1_seed": "W99", "team2_seed": "W100", "venue": "Mercedes-Benz Stadium, Atlanta", "top10": true, "top20": true },
    { "match_id": 103, "group": "Third-place match", "date": "18/7", "time": "07:30", "team1": "Loser Match 101", "team2": "Loser Match 102", "team1_seed": "L101", "team2_seed": "L102", "venue": "Hard Rock Stadium, Miami Gardens", "top10": false, "top20": true },
    { "match_id": 104, "group": "Final", "date": "19/7", "time": "07:30", "team1": "Winner Match 101", "team2": "Winner Match 102", "team1_seed": "W101", "team2_seed": "W102", "venue": "MetLife Stadium, East Rutherford", "top10": true, "top20": true }
  ],
  "bracket_rules": {
    "round_of_32": [
      { "match": 73, "home": "Runner-up Group A", "away": "Runner-up Group B" },
      { "match": 74, "home": "Winner Group E", "away": "3rd Group A/B/C/D/F" },
      { "match": 75, "home": "Winner Group F", "away": "Runner-up Group C" },
      { "match": 76, "home": "Winner Group C", "away": "Runner-up Group F" },
      { "match": 77, "home": "Winner Group I", "away": "3rd Group C/D/F/G/H" },
      { "match": 78, "home": "Runner-up Group E", "away": "Runner-up Group I" },
      { "match": 79, "home": "Winner Group A", "away": "3rd Group C/E/F/H/I" },
      { "match": 80, "home": "Winner Group L", "away": "3rd Group E/F/G/I/J" },
      { "match": 81, "home": "Winner Group D", "away": "3rd Group B/E/F/I/J" },
      { "match": 82, "home": "Winner Group G", "away": "3rd Group A/E/H/I/J" },
      { "match": 83, "home": "Runner-up Group K", "away": "Runner-up Group L" },
      { "match": 84, "home": "Winner Group H", "away": "Runner-up Group J" },
      { "match": 85, "home": "Winner Group B", "away": "3rd Group A/C/D/F/G" },
      { "match": 86, "home": "Winner Group J", "away": "Runner-up Group H" },
      { "match": 87, "home": "Winner Group K", "away": "3rd Group D/E/I/J/L" },
      { "match": 88, "home": "Runner-up Group D", "away": "Runner-up Group G" }
    ],
    "round_of_16": [
      { "match": 89, "home": "Winner Match 73", "away": "Winner Match 74" },
      { "match": 90, "home": "Winner Match 75", "away": "Winner Match 76" },
      { "match": 91, "home": "Winner Match 77", "away": "Winner Match 78" },
      { "match": 92, "home": "Winner Match 79", "away": "Winner Match 80" },
      { "match": 93, "home": "Winner Match 81", "away": "Winner Match 82" },
      { "match": 94, "home": "Winner Match 83", "away": "Winner Match 84" },
      { "match": 95, "home": "Winner Match 85", "away": "Winner Match 86" },
      { "match": 96, "home": "Winner Match 87", "away": "Winner Match 88" }
    ],
    "quarter_finals": [
      { "match": 97, "home": "Winner Match 89", "away": "Winner Match 90" },
      { "match": 98, "home": "Winner Match 93", "away": "Winner Match 94" },
      { "match": 99, "home": "Winner Match 91", "away": "Winner Match 92" },
      { "match": 100, "home": "Winner Match 95", "away": "Winner Match 96" }
    ],
    "semi_finals": [
      { "match": 101, "home": "Winner Match 97", "away": "Winner Match 98" },
      { "match": 102, "home": "Winner Match 99", "away": "Winner Match 100" }
    ],
    "third_place": [
      { "match": 103, "home": "Loser Match 101", "away": "Loser Match 102" }
    ],
    "final": [
      { "match": 104, "home": "Winner Match 101", "away": "Winner Match 102" }
    ]
  }
};
