// FIFA World Cup 2026 Schedule & Settings Data (Indonesian Translation)

window.TEAM_FLAGS = {
  "Meksiko": "mx",
  "Afrika Selatan": "za",
  "Korea Selatan": "kr",
  "Ceko": "cz",
  "Kanada": "ca",
  "Bosnia dan Herzegovina": "ba",
  "Qatar": "qa",
  "Swiss": "ch",
  "Brasil": "br",
  "Maroko": "ma",
  "Haiti": "ht",
  "Skotlandia": "gb-sct",
  "Amerika Serikat": "us",
  "Paraguay": "py",
  "Australia": "au",
  "Turki": "tr",
  "Jerman": "de",
  "Curaçao": "cw",
  "Belanda": "nl",
  "Jepang": "jp",
  "Pantai Gading": "ci",
  "Ekuador": "ec",
  "Swedia": "se",
  "Tunisia": "tn",
  "Spanyol": "es",
  "Tanjung Verde": "cv",
  "Belgia": "be",
  "Mesir": "eg",
  "Arab Saudi": "sa",
  "Uruguay": "uy",
  "Iran": "ir",
  "Selandia Baru": "nz",
  "Prancis": "fr",
  "Senegal": "sn",
  "Irak": "iq",
  "Norwegia": "no",
  "Argentina": "ar",
  "Aljazair": "dz",
  "Austria": "at",
  "Yordania": "jo",
  "Portugal": "pt",
  "RD Kongo": "cd",
  "Inggris": "gb-eng",
  "Kroasia": "hr",
  "Ghana": "gh",
  "Panama": "pa",
  "Uzbekistan": "uz",
  "Kolombia": "co"
};

window.TEAM_COLORS = {
  "Meksiko": ["#006341", "#ffffff", "#c8102e"],
  "Afrika Selatan": ["#007c59", "#ffb81c", "#ffffff"],
  "Korea Selatan": ["#cd2e3a", "#0047a0", "#ffffff"],
  "Ceko": ["#d90012", "#ffffff", "#11457e"],
  "Kanada": ["#da291c", "#ffffff"],
  "Bosnia dan Herzegovina": ["#00209f", "#fecb00", "#ffffff"],
  "Qatar": ["#8a1538", "#ffffff"],
  "Swiss": ["#da291c", "#ffffff"],
  "Brasil": ["#009c3b", "#ffdf00", "#002776"],
  "Maroko": ["#c1272d", "#006233"],
  "Haiti": ["#00209f", "#ffffff", "#d21034"],
  "Skotlandia": ["#002b5c", "#ffffff"],
  "Amerika Serikat": ["#002868", "#ffffff", "#bf0a30"],
  "Paraguay": ["#d52b1e", "#ffffff", "#0038a8"],
  "Australia": ["#00843d", "#ffcd00"],
  "Turki": ["#e30a17", "#ffffff"],
  "Jerman": ["#000000", "#dd0000", "#ffcf00"],
  "Curaçao": ["#002b7f", "#f9e300", "#ffffff"],
  "Belanda": ["#f36c21", "#ffffff", "#21468b"],
  "Jepang": ["#004b87", "#ffffff", "#bc002d"],
  "Pantai Gading": ["#ff8200", "#ffffff", "#009e60"],
  "Ekuador": ["#ffdd00", "#0033a0", "#d52b1e"],
  "Swedia": ["#006aa7", "#fecc00"],
  "Tunisia": ["#e20919", "#ffffff"],
  "Spanyol": ["#ad1519", "#fabd00"],
  "Tanjung Verde": ["#002a6f", "#ffffff", "#d21034"],
  "Belgia": ["#2d2926", "#ffd100", "#f1182c"],
  "Mesir": ["#ce1126", "#ffffff", "#000000"],
  "Arab Saudi": ["#006c35", "#ffffff"],
  "Uruguay": ["#0081c6", "#ffffff"],
  "Iran": ["#239e46", "#ffffff", "#da291c"],
  "Selandia Baru": ["#000000", "#ffffff"],
  "Prancis": ["#002395", "#ffffff", "#ed2939"],
  "Senegal": ["#00853f", "#fcd116", "#e31b23"],
  "Irak": ["#e31b23", "#ffffff", "#000000"],
  "Norwegia": ["#ba0c2f", "#ffffff", "#00205b"],
  "Argentina": ["#75aadb", "#ffffff"],
  "Aljazair": ["#006233", "#ffffff", "#d21034"],
  "Austria": ["#ed2939", "#ffffff"],
  "Yordania": ["#000000", "#ffffff", "#ce1126"],
  "Portugal": ["#006600", "#ff0000"],
  "RD Kongo": ["#007fff", "#ce1126"],
  "Inggris": ["#ffffff", "#da291c"],
  "Kroasia": ["#ff0000", "#ffffff", "#00209f"],
  "Ghana": ["#da291c", "#fcd116", "#006b3f"],
  "Panama": ["#da291c", "#ffffff", "#005293"],
  "Uzbekistan": ["#00aeef", "#ffffff", "#1eb53a"],
  "Kolombia": ["#fcd116", "#003893", "#ce1126"]
};


window.WORLD_CUP_DATA = {
  "tournament": "FIFA World Cup 2026",
  "teams_count": 48,
  "total_matches": 104,
  "group_stage": [
    { "group": "Grup A", "date": "12/6", "time": "02:00", "team1": "Meksiko", "team2": "Afrika Selatan" },
    { "group": "Grup A", "date": "12/6", "time": "09:00", "team1": "Korea Selatan", "team2": "Ceko" },
    { "group": "Grup B", "date": "13/6", "time": "02:00", "team1": "Kanada", "team2": "Bosnia dan Herzegovina" },
    { "group": "Grup D", "date": "13/6", "time": "08:00", "team1": "Amerika Serikat", "team2": "Paraguay" },
    { "group": "Grup B", "date": "14/6", "time": "02:00", "team1": "Qatar", "team2": "Swiss" },
    { "group": "Grup C", "date": "14/6", "time": "05:00", "team1": "Brasil", "team2": "Maroko" },
    { "group": "Grup C", "date": "14/6", "time": "08:00", "team1": "Haiti", "team2": "Skotlandia" },
    { "group": "Grup D", "date": "14/6", "time": "11:00", "team1": "Australia", "team2": "Turki" },
    { "group": "Grup E", "date": "15/6", "time": "00:00", "team1": "Jerman", "team2": "Curaçao" },
    { "group": "Grup F", "date": "15/6", "time": "03:00", "team1": "Belanda", "team2": "Jepang" },
    { "group": "Grup E", "date": "15/6", "time": "06:00", "team1": "Pantai Gading", "team2": "Ekuador" },
    { "group": "Grup F", "date": "15/6", "time": "09:00", "team1": "Swedia", "team2": "Tunisia" },
    { "group": "Grup H", "date": "15/6", "time": "23:00", "team1": "Spanyol", "team2": "Tanjung Verde" },
    { "group": "Grup G", "date": "16/6", "time": "02:00", "team1": "Belgia", "team2": "Mesir" },
    { "group": "Grup H", "date": "16/6", "time": "05:00", "team1": "Arab Saudi", "team2": "Uruguay" },
    { "group": "Grup G", "date": "16/6", "time": "08:00", "team1": "Iran", "team2": "Selandia Baru" },
    { "group": "Grup I", "date": "17/6", "time": "02:00", "team1": "Prancis", "team2": "Senegal" },
    { "group": "Grup I", "date": "17/6", "time": "05:00", "team1": "Irak", "team2": "Norwegia" },
    { "group": "Grup J", "date": "17/6", "time": "08:00", "team1": "Argentina", "team2": "Aljazair" },
    { "group": "Grup J", "date": "17/6", "time": "11:00", "team1": "Austria", "team2": "Yordania" },
    { "group": "Grup K", "date": "18/6", "time": "00:00", "team1": "Portugal", "team2": "RD Kongo" },
    { "group": "Grup L", "date": "18/6", "time": "03:00", "team1": "Inggris", "team2": "Kroasia" },
    { "group": "Grup L", "date": "18/6", "time": "06:00", "team1": "Ghana", "team2": "Panama" },
    { "group": "Grup K", "date": "18/6", "time": "09:00", "team1": "Uzbekistan", "team2": "Kolombia" },
    { "group": "Grup A", "date": "18/6", "time": "23:00", "team1": "Ceko", "team2": "Afrika Selatan" },
    { "group": "Grup B", "date": "19/6", "time": "02:00", "team1": "Swiss", "team2": "Bosnia dan Herzegovina" },
    { "group": "Grup B", "date": "19/6", "time": "05:00", "team1": "Kanada", "team2": "Qatar" },
    { "group": "Grup A", "date": "19/6", "time": "08:00", "team1": "Meksiko", "team2": "Korea Selatan" },
    { "group": "Grup D", "date": "20/6", "time": "02:00", "team1": "Amerika Serikat", "team2": "Australia" },
    { "group": "Grup C", "date": "20/6", "time": "05:00", "team1": "Skotlandia", "team2": "Maroko" },
    { "group": "Grup C", "date": "20/6", "time": "07:30", "team1": "Brasil", "team2": "Haiti" },
    { "group": "Grup D", "date": "20/6", "time": "10:00", "team1": "Turki", "team2": "Paraguay" },
    { "group": "Grup F", "date": "21/6", "time": "00:00", "team1": "Belanda", "team2": "Swedia" },
    { "group": "Grup E", "date": "21/6", "time": "03:00", "team1": "Jerman", "team2": "Pantai Gading" },
    { "group": "Grup E", "date": "21/6", "time": "07:00", "team1": "Ekuador", "team2": "Curaçao" },
    { "group": "Grup F", "date": "21/6", "time": "11:00", "team1": "Tunisia", "team2": "Jepang" },
    { "group": "Grup H", "date": "21/6", "time": "23:00", "team1": "Spanyol", "team2": "Arab Saudi" },
    { "group": "Grup G", "date": "22/6", "time": "02:00", "team1": "Belgia", "team2": "Iran" },
    { "group": "Grup H", "date": "22/6", "time": "05:00", "team1": "Uruguay", "team2": "Tanjung Verde" },
    { "group": "Grup G", "date": "22/6", "time": "08:00", "team1": "Selandia Baru", "team2": "Mesir" },
    { "group": "Grup J", "date": "23/6", "time": "00:00", "team1": "Argentina", "team2": "Austria" },
    { "group": "Grup I", "date": "23/6", "time": "04:00", "team1": "Prancis", "team2": "Irak" },
    { "group": "Grup I", "date": "23/6", "time": "07:00", "team1": "Norwegia", "team2": "Senegal" },
    { "group": "Grup J", "date": "23/6", "time": "10:00", "team1": "Yordania", "team2": "Aljazair" },
    { "group": "Grup K", "date": "24/6", "time": "00:00", "team1": "Portugal", "team2": "Uzbekistan" },
    { "group": "Grup L", "date": "24/6", "time": "03:00", "team1": "Inggris", "team2": "Ghana" },
    { "group": "Grup L", "date": "24/6", "time": "06:00", "team1": "Panama", "team2": "Kroasia" },
    { "group": "Grup K", "date": "24/6", "time": "09:00", "team1": "Kolombia", "team2": "RD Kongo" },
    { "group": "Grup B", "date": "25/6", "time": "02:00", "team1": "Swiss", "team2": "Kanada" },
    { "group": "Grup B", "date": "25/6", "time": "02:00", "team1": "Bosnia dan Herzegovina", "team2": "Qatar" },
    { "group": "Grup C", "date": "25/6", "time": "05:00", "team1": "Maroko", "team2": "Haiti" },
    { "group": "Grup C", "date": "25/6", "time": "05:00", "team1": "Skotlandia", "team2": "Brasil" },
    { "group": "Grup A", "date": "25/6", "time": "08:00", "team1": "Afrika Selatan", "team2": "Korea Selatan" },
    { "group": "Grup A", "date": "25/6", "time": "08:00", "team1": "Ceko", "team2": "Meksiko" },
    { "group": "Grup E", "date": "26/6", "time": "03:00", "team1": "Curaçao", "team2": "Pantai Gading" },
    { "group": "Grup E", "date": "26/6", "time": "03:00", "team1": "Ekuador", "team2": "Jerman" },
    { "group": "Grup F", "date": "26/6", "time": "06:00", "team1": "Tunisia", "team2": "Belanda" },
    { "group": "Grup F", "date": "26/6", "time": "06:00", "team1": "Jepang", "team2": "Swedia" },
    { "group": "Grup D", "date": "26/6", "time": "09:00", "team1": "Turki", "team2": "Amerika Serikat" },
    { "group": "Grup D", "date": "26/6", "time": "09:00", "team1": "Paraguay", "team2": "Australia" },
    { "group": "Grup I", "date": "27/6", "time": "02:00", "team1": "Norwegia", "team2": "Prancis" },
    { "group": "Grup I", "date": "27/6", "time": "02:00", "team1": "Senegal", "team2": "Irak" },
    { "group": "Grup H", "date": "27/6", "time": "07:00", "team1": "Tanjung Verde", "team2": "Arab Saudi" },
    { "group": "Grup H", "date": "27/6", "time": "07:00", "team1": "Uruguay", "team2": "Spanyol" },
    { "group": "Grup G", "date": "27/6", "time": "10:00", "team1": "Selandia Baru", "team2": "Belgia" },
    { "group": "Grup G", "date": "27/6", "time": "10:00", "team1": "Mesir", "team2": "Iran" },
    { "group": "Grup L", "date": "28/6", "time": "04:00", "team1": "Panama", "team2": "Inggris" },
    { "group": "Grup L", "date": "28/6", "time": "04:00", "team1": "Kroasia", "team2": "Ghana" },
    { "group": "Grup K", "date": "28/6", "time": "06:30", "team1": "Kolombia", "team2": "Portugal" },
    { "group": "Grup K", "date": "28/6", "time": "06:30", "team1": "RD Kongo", "team2": "Uzbekistan" },
    { "group": "Grup J", "date": "28/6", "time": "09:00", "team1": "Aljazair", "team2": "Austria" },
    { "group": "Grup J", "date": "28/6", "time": "09:00", "team1": "Yordania", "team2": "Argentina" }
  ],
  "knockout_stage": [
    { "match_id": 73, "group": "Round of 32", "date": "29/6", "time": "02:00", "team1": "Afrika Selatan", "team2": "Kanada", "team1_seed": "2A", "team2_seed": "2B", "venue": "SoFi Stadium, Inglewood", "top10": false, "top20": true },
    { "match_id": 74, "group": "Round of 32", "date": "30/6", "time": "03:30", "team1": "Jerman", "team2": "Paraguay", "team1_seed": "1E", "team2_seed": "3rd", "venue": "Gillette Stadium, Foxborough", "top10": false, "top20": true },
    { "match_id": 75, "group": "Round of 32", "date": "30/6", "time": "08:00", "team1": "Belanda", "team2": "Maroko", "team1_seed": "1F", "team2_seed": "2C", "venue": "Estadio BBVA, Monterrey", "top10": false, "top20": true },
    { "match_id": 76, "group": "Round of 32", "date": "30/6", "time": "00:00", "team1": "Brasil", "team2": "Jepang", "team1_seed": "1C", "team2_seed": "2F", "venue": "NRG Stadium, Houston", "top10": false, "top20": true },
    { "match_id": 77, "group": "Round of 32", "date": "1/7", "time": "04:00", "team1": "Prancis", "team2": "Swedia", "team1_seed": "1I", "team2_seed": "3rd", "venue": "MetLife Stadium, East Rutherford", "top10": false, "top20": true },
    { "match_id": 78, "group": "Round of 32", "date": "1/7", "time": "00:00", "team1": "Pantai Gading", "team2": "Norwegia", "team1_seed": "2E", "team2_seed": "2I", "venue": "AT&T Stadium, Arlington", "top10": false, "top20": true },
    { "match_id": 79, "group": "Round of 32", "date": "1/7", "time": "08:00", "team1": "Meksiko", "team2": "3rd Grup C/E/F/H/I", "team1_seed": "1A", "team2_seed": "3rd", "venue": "Estadio Azteca, Mexico City", "top10": false, "top20": true },
    { "match_id": 80, "group": "Round of 32", "date": "1/7", "time": "23:00", "team1": "Juara Grup L", "team2": "3rd Grup E/H/I/J/K", "team1_seed": "1L", "team2_seed": "3rd", "venue": "Mercedes-Benz Stadium, Atlanta", "top10": false, "top20": true },
    { "match_id": 81, "group": "Round of 32", "date": "2/7", "time": "07:00", "team1": "Amerika Serikat", "team2": "Bosnia dan Herzegovina", "team1_seed": "1D", "team2_seed": "3rd", "venue": "Levi's Stadium, Santa Clara", "top10": false, "top20": true },
    { "match_id": 82, "group": "Round of 32", "date": "2/7", "time": "03:00", "team1": "Juara Grup G", "team2": "3rd Grup A/E/H/I/J", "team1_seed": "1G", "team2_seed": "3rd", "venue": "Lumen Field, Seattle", "top10": false, "top20": true },
    { "match_id": 83, "group": "Round of 32", "date": "3/7", "time": "06:00", "team1": "Runner-up Grup K", "team2": "Runner-up Grup L", "team1_seed": "2K", "team2_seed": "2L", "venue": "BMO Field, Toronto", "top10": false, "top20": true },
    { "match_id": 84, "group": "Round of 32", "date": "3/7", "time": "02:00", "team1": "Spanyol", "team2": "Runner-up Grup J", "team1_seed": "1H", "team2_seed": "2J", "venue": "SoFi Stadium, Inglewood", "top10": false, "top20": true },
    { "match_id": 85, "group": "Round of 32", "date": "3/7", "time": "10:00", "team1": "Swiss", "team2": "3rd Grup E/F/G/I/J", "team1_seed": "1B", "team2_seed": "3rd", "venue": "BC Place, Vancouver", "top10": false, "top20": true },
    { "match_id": 86, "group": "Round of 32", "date": "4/7", "time": "05:00", "team1": "Argentina", "team2": "Tanjung Verde", "team1_seed": "1J", "team2_seed": "2H", "venue": "Hard Rock Stadium, Miami", "top10": false, "top20": true },
    { "match_id": 87, "group": "Round of 32", "date": "4/7", "time": "08:30", "team1": "Juara Grup K", "team2": "3rd Grup D/E/I/J/L", "team1_seed": "1K", "team2_seed": "3rd", "venue": "Arrowhead Stadium, Kansas City", "top10": false, "top20": true },
    { "match_id": 88, "group": "Round of 32", "date": "4/7", "time": "01:00", "team1": "Australia", "team2": "Runner-up Grup G", "team1_seed": "2D", "team2_seed": "2G", "venue": "AT&T Stadium, Arlington", "top10": false, "top20": true },
    { "match_id": 89, "group": "Round of 16", "date": "5/7", "time": "04:00", "team1": "Winner Match 74", "team2": "Winner Match 77", "team1_seed": "W74", "team2_seed": "W77", "venue": "Lincoln Financial Field, Philadelphia", "top10": false, "top20": true },
    { "match_id": 90, "group": "Round of 16", "date": "5/7", "time": "00:00", "team1": "Winner Match 73", "team2": "Winner Match 75", "team1_seed": "W73", "team2_seed": "W75", "venue": "NRG Stadium, Houston", "top10": false, "top20": true },
    { "match_id": 91, "group": "Round of 16", "date": "6/7", "time": "03:00", "team1": "Winner Match 76", "team2": "Winner Match 78", "team1_seed": "W76", "team2_seed": "W78", "venue": "MetLife Stadium, East Rutherford", "top10": false, "top20": true },
    { "match_id": 92, "group": "Round of 16", "date": "5/7", "time": "07:00", "team1": "Winner Match 79", "team2": "Winner Match 80", "team1_seed": "W79", "team2_seed": "W80", "venue": "Estadio Banorte, Mexico City", "top10": false, "top20": true },
    { "match_id": 93, "group": "Round of 16", "date": "7/7", "time": "02:00", "team1": "Winner Match 83", "team2": "Winner Match 84", "team1_seed": "W83", "team2_seed": "W84", "venue": "AT&T Stadium, Arlington", "top10": false, "top20": true },
    { "match_id": 94, "group": "Round of 16", "date": "7/7", "time": "07:00", "team1": "Winner Match 81", "team2": "Winner Match 82", "team1_seed": "W81", "team2_seed": "W82", "venue": "Lumen Field, Seattle", "top10": false, "top20": true },
    { "match_id": 95, "group": "Round of 16", "date": "7/7", "time": "23:00", "team1": "Winner Match 86", "team2": "Winner Match 88", "team1_seed": "W86", "team2_seed": "W88", "venue": "Mercedes-Benz Stadium, Atlanta", "top10": false, "top20": true },
    { "match_id": 96, "group": "Round of 16", "date": "8/7", "time": "03:00", "team1": "Winner Match 85", "team2": "Winner Match 87", "team1_seed": "W85", "team2_seed": "W87", "venue": "BC Place, Vancouver", "top10": false, "top20": true },
    { "match_id": 97, "group": "Quarter-final", "date": "10/7", "time": "03:00", "team1": "Winner Match 89", "team2": "Winner Match 90", "team1_seed": "W89", "team2_seed": "W90", "venue": "Gillette Stadium, Foxborough", "top10": true, "top20": true },
    { "match_id": 98, "group": "Quarter-final", "date": "11/7", "time": "02:00", "team1": "Winner Match 93", "team2": "Winner Match 94", "team1_seed": "W93", "team2_seed": "W94", "venue": "SoFi Stadium, Inglewood", "top10": true, "top20": true },
    { "match_id": 99, "group": "Quarter-final", "date": "12/7", "time": "04:00", "team1": "Winner Match 91", "team2": "Winner Match 92", "team1_seed": "W91", "team2_seed": "W92", "venue": "Hard Rock Stadium, Miami", "top10": true, "top20": true },
    { "match_id": 100, "group": "Quarter-final", "date": "12/7", "time": "08:00", "team1": "Winner Match 95", "team2": "Winner Match 96", "team1_seed": "W95", "team2_seed": "W96", "venue": "Arrowhead Stadium, Kansas City", "top10": true, "top20": true },
    { "match_id": 101, "group": "Semi-final", "date": "15/7", "time": "02:00", "team1": "Winner Match 97", "team2": "Winner Match 98", "team1_seed": "W97", "team2_seed": "W98", "venue": "AT&T Stadium, Arlington", "top10": true, "top20": true },
    { "match_id": 102, "group": "Semi-final", "date": "16/7", "time": "02:00", "team1": "Winner Match 99", "team2": "Winner Match 100", "team1_seed": "W99", "team2_seed": "W100", "venue": "Mercedes-Benz Stadium, Atlanta", "top10": true, "top20": true },
    { "match_id": 103, "group": "Third-place match", "date": "19/7", "time": "04:00", "team1": "Loser Match 101", "team2": "Loser Match 102", "team1_seed": "L101", "team2_seed": "L102", "venue": "Hard Rock Stadium, Miami", "top10": false, "top20": true },
    { "match_id": 104, "group": "Final", "date": "20/7", "time": "02:00", "team1": "Winner Match 101", "team2": "Winner Match 102", "team1_seed": "W101", "team2_seed": "W102", "venue": "MetLife Stadium, East Rutherford", "top10": true, "top20": true }
  ],
  "bracket_rules": {
    "round_of_32": [
      { "match": 73, "home": "Runner-up Grup A", "away": "Runner-up Grup B" },
      { "match": 74, "home": "Juara Grup E", "away": "3rd Grup A/B/C/D/F" },
      { "match": 75, "home": "Juara Grup F", "away": "Runner-up Grup C" },
      { "match": 76, "home": "Juara Grup C", "away": "Runner-up Grup F" },
      { "match": 77, "home": "Juara Grup I", "away": "3rd Grup C/D/F/G/H" },
      { "match": 78, "home": "Runner-up Grup E", "away": "Runner-up Grup I" },
      { "match": 79, "home": "Juara Grup A", "away": "3rd Grup C/E/F/H/I" },
      { "match": 80, "home": "Juara Grup L", "away": "3rd Grup E/H/I/J/K" },
      { "match": 81, "home": "Juara Grup D", "away": "3rd Grup B/E/F/I/J" },
      { "match": 82, "home": "Juara Grup G", "away": "3rd Grup A/E/H/I/J" },
      { "match": 83, "home": "Runner-up Grup K", "away": "Runner-up Grup L" },
      { "match": 84, "home": "Juara Grup H", "away": "Runner-up Grup J" },
      { "match": 85, "home": "Juara Grup B", "away": "3rd Grup E/F/G/I/J" },
      { "match": 86, "home": "Juara Grup J", "away": "Runner-up Grup H" },
      { "match": 87, "home": "Juara Grup K", "away": "3rd Grup D/E/I/J/L" },
      { "match": 88, "home": "Runner-up Grup D", "away": "Runner-up Grup G" }
    ],
    "round_of_16": [
      { "match": 89, "home": "Winner Match 74", "away": "Winner Match 77" },
      { "match": 90, "home": "Winner Match 73", "away": "Winner Match 75" },
      { "match": 91, "home": "Winner Match 76", "away": "Winner Match 78" },
      { "match": 92, "home": "Winner Match 79", "away": "Winner Match 80" },
      { "match": 93, "home": "Winner Match 83", "away": "Winner Match 84" },
      { "match": 94, "home": "Winner Match 81", "away": "Winner Match 82" },
      { "match": 95, "home": "Winner Match 86", "away": "Winner Match 88" },
      { "match": 96, "home": "Winner Match 85", "away": "Winner Match 87" }
    ],
    "quarter_finals": [
      { "match": 97, "home": "Winner Match 89", "away": "Winner Match 90" },
      { "match": 98, "home": "Winner Match 93", "away": "Winner Match 94" },
      { "match": 99, "home": "Winner Match 91", "away": "Winner Match 92" },
      { "match": 100, "home": "Winner Match 95", "away": "Winner Match 96" }
    ],
    "semi_finals": [
      { "match": 101, "home": "Winner Match 97", "away": "Winner Match 98" },
      { "match": 102, "home": "Winner Match 99", "away": "Winner Match 100" }
    ],
    "third_place": [
      { "match": 103, "home": "Loser Match 101", "away": "Loser Match 102" }
    ],
    "final": [
      { "match": 104, "home": "Winner Match 101", "away": "Winner Match 102" }
    ]
  }
};
